services:
  app:
    build: .
    ports:
      - "8017:7017"
    environment:
      - MONGO_URI=mongodb://mongo:27017/hirebuddy
    depends_on:
      mongo:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7017/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
