version: '3.8'

services:
  app:
    build: .
    ports:
      - "7017:7017"
    environment:
      - MONGO_URI=mongodb://mongo:27017/hirebuddy
    depends_on:
      - mongo
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7017/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
