apiVersion: v1
kind: Service
metadata:
  name: hirebuddy-service
spec:
  type: NodePort
  selector:
    app: hirebuddy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007